version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8000:8000
    env_file: ./docker/backend/.env
    volumes:
      - ./backend/:/srv/app
    depends_on:
      - db
      
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file: ./docker/db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - public_html:/var/www/html
    depends_on:
      - backend
      - db
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    env_file:
      - ./docker/frontend/.env
    volumes:
      - ./frontend/:/srv/app
      - public_html:/var/www/html
    depends_on:
      - backend
      - db

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  public_html: